### PR TITLE
Bump openTelemetryVersion to 1.15.0

### PR DESCRIPTION
**Pull request by dgnemo**

### CODE REVIEW

**Comment by dgnemo** [comment]
CLA signed

**Comment by jsuereth** [comment]
Hey!  Thanks for the PR.  We're doing a bit more cleanup with this release, which you can see in #154.   This includes removing the -alpha. 

Thanks for the contribution!

**Comment by dgnemo** [comment]
Sure, looking forward to https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/pull/154 being merged.

**Pull request closed without merging**
