### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by hsl43**
Fixing values for `otel.traces.exporter` and `otel.metrics.exporter` in table view to be consistent with AutoInstrumentation Setup section

### CODE REVIEW

**Comment by punya** [comment]
@hsl43 thanks for the correction! I know it's a tiny change, but would you mind following the instructions to sign the CLA?

**Comment by hsl43** [comment]
@googlebot I signed it!

**Review by jsuereth — APPROVED** [review]

**Pull request merged**
